db:
    image: postgres
    restart: always
    ports:
        - 5555:5432
    environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: docker
api:
    image: plant-api
    restart: always
    ports:
        - 80
    links:
        - db
web:
    image: plant-web
    restart: always
    links: 
        - api 
    ports:
        - 8080
