proxy:
    image: host-proxy
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
db:
    image: postgres
    restart: always
    ports:
        - 5555:5432
    environment:
        POSTGRES_PASSWORD: dodocker
        POSTGRES_USER: docker
api:
    image: plant-api
    restart: always
    environment:
       - VIRTUAL_HOST=api.millstplantsale.com
       - DATABASE_URL=postgres://docker:FIXME@db/docker
       - STRIPE_KEY=sk_live_asdfasdfasdfasdfasd
    ports:
        - 80
    links:
        - db
web:
    image: plant-web
    restart: always
    links: 
        - api 
    environment:
       - VIRTUAL_HOST=www.millstplantsale.com,millstplantsale.com
    ports:
        - 8080
        - 80
