proxy:
    image: host-proxy
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes: 
        - /var/run/docker.sock:/tmp/docker.sock
db:
    image: postgres
    restart: always
    ports:
        - 5555:5432
    environment:
        POSTGRES_PASSWORD: dodocker
        POSTGRES_USER: docker
api:
    image: plant-api
    restart: always
    environment:
       - DATABASE_URL=postgres://docker:dodocker@db/docker
       - STRIPE_KEY=sk_live_ asldkfjlaskdjflkjalsdkfj
    ports:
        - 80
    links:
        - db
web:
    image: plant-web
    restart: always
    links: 
        - api 
    environment:
       - VIRTUAL_HOST=www.millstplantsale.com,millstplantsale.com
    ports:
        - 8080
        - 80
