# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 5, 16, 56, 22, 49227, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
