# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20160309_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='marketing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
