# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
