# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20160313_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='times',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
