# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_stakeholder_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 9, 3, 24, 20, 28286, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='color_limits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='color_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
