# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20160309_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
