# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20160311_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
