# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20160320_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
